### ISSUE TITLE
Support SSL connection for MySQL

### ISSUE THREAD

**Issue by richardeee** [sqlchat/sqlchat#12]
### Describe the bug

在创建MySQL连接时，如果使用SSL，会提示错误:

```
Ignoring invalid configuration option passed to Connection: useSSL. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Add command: ClientHandshake
 raw: 0a352e372e34312d6c6f67002f0000004179366c276a383200ffff080200ffc1150000000000000000000020722d347b547e5a385c3c64006d7973716c5f6e61746976655f70617373776f726400
Trace
    at Connection.handlePacket (D:\Code\AzureSQLChatGPTDemo\node_modules\.pnpm\mysql2@3.2.0\node_modules\mysql2\lib\connection.js:446:17)
    at PacketParser.onPacket (D:\Code\AzureSQLChatGPTDemo\node_modules\.pnpm\mysql2@3.2.0\node_modules\mysql2\lib\connection.js:94:12)
    at PacketParser.executeStart (D:\Code\AzureSQLChatGPTDemo\node_modules\.pnpm\mysql2@3.2.0\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (D:\Code\AzureSQLChatGPTDemo\node_modules\.pnpm\mysql2@3.2.0\node_modules\mysql2\lib\connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
6 undefined ==> ClientHandshake#unknown name(0,,82)
Server hello packet: capability flags:3254779903=(long password, found rows, long flag, connect with db, no schema, compress, odbc, local files, ignore space, protocol 41, interactive, ssl, ignore sigpipe, transactions, reserved, secure connection, multi statements, multi results, ps multi results, plugin auth, connect attrs, plugin auth lenenc client data, can handle expired passwords, session track, deprecate eof, ssl verify server cert, remember options)
Sending handshake packet: flags:12252111=(long password, found rows, long flag, connect with db, odbc, local files, ignore space, protocol 41, ignore sigpipe, transactions, reserved, secure connection, multi results, plugin auth, connect attrs, plugin auth lenenc client data, session track)
6 47 <== ClientHandshake#unknown name(1,,127)
6 47 <== 7b000001cff3ba0000000000e0000000000000000000000000000000000000000000000061646d696e757365720000656d706c6f796565006d7973716c5f6e61746976655f70617373776f726400300c5f636c69656e745f6e616d650c4e6f64652d4d7953514c2d320f5f636c69656e745f76657273696f6e05332e322e30
 raw: ff15042332383030304163636573732064656e69656420666f722075736572202761646d696e757365722740273132302e3232392e37382e3131352720287573696e672070617373776f72643a204e4f29
Trace
    at Connection.handlePacket (D:\Code\AzureSQLChatGPTDemo\node_modules\.pnpm\mysql2@3.2.0\node_modules\mysql2\lib\connection.js:446:17)
    at PacketParser.onPacket (D:\Code\AzureSQLChatGPTDemo\node_modules\.pnpm\mysql2@3.2.0\node_modules\mysql2\lib\connection.js:94:12)
    at PacketParser.executeStart (D:\Code\AzureSQLChatGPTDemo\node_modules\.pnpm\mysql2@3.2.0\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (D:\Code\AzureSQLChatGPTDemo\node_modules\.pnpm\mysql2@3.2.0\node_modules\mysql2\lib\connection.js:101:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
6 47 ==> ClientHandshake#unknown name(2,Error,85)
```
我修改了lib/connectors/mysql/index.ts
```typescript
const getMySQLConnection = async (connection: Connection): Promise<mysql.Connection> => {
  // const connectionUrl = convertToConnectionUrl(connection);
  // const conn = await mysql.createConnection(connectionUrl);
  const serverCa = [fs.readFileSync(path.join(__dirname, "/cert/DigiCertGlobalRootCA.crt.pem"), "utf8")];

  console.log(serverCa)

  const conn = await mysql.createConnection({
    host: connection.host,
    port: parseInt(connection.port),
    user: connection.username,
    password: connection.password,
    database: connection.database,
    debug:true,
    ssl: {
      rejectUnauthorized: false,
      ca: serverCa
    }
  });

  return conn;
};
```

### To reproduce

不使用url的方法，创建一个新的function：
```typescript
const getMySQLConnection = async (connection: Connection): Promise<mysql.Connection> => {
  // const connectionUrl = convertToConnectionUrl(connection);
  // const conn = await mysql.createConnection(connectionUrl);
  const serverCa = [fs.readFileSync(path.join(__dirname, "/cert/DigiCertGlobalRootCA.crt.pem"), "utf8")];

  console.log(serverCa)

  const conn = await mysql.createConnection({
    host: connection.host,
    port: parseInt(connection.port),
    user: connection.username,
    password: connection.password,
    database: connection.database,
    debug:true,
    ssl: {
      rejectUnauthorized: false,
      ca: serverCa
    }
  });

  return conn;
};
```
点击Create Connection，填写信息，保存，查看后台日志。

**Comment by boojack** [comment]
Thanks for your solution. We'll add a SSL related field in Connection.
