### ISSUE TITLE
installdocker

### ISSUE THREAD

**Issue by WQMysqlDBA** [sqlchat/sqlchat#130]
### Describe the bug

Listening on port 3000 url: http://9f360ba7399b:3000
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/app/node_modules/.pnpm/@prisma+client@4.13.0_prisma@4.13.0/node_modules/.prisma/client/index.js:3:11)
    at 2415 (/app/.next/server/chunks/415.js:18:16)
    at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:25:42)
    at 639 (/app/.next/server/chunks/639.js:26:77)
    at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:25:42)
    at __webpack_exec__ (/app/.next/server/pages/api/auth/[...nextauth].js:56:39)
    at /app/.next/server/pages/api/auth/[...nextauth].js:57:70
    at __webpack_require__.X (/app/.next/server/webpack-api-runtime.js:177:21)
    at /app/.next/server/pages/api/auth/[...nextauth].js:57:47
    at Object.<anonymous> (/app/.next/server/pages/api/auth/[...nextauth].js:60:3)
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/app/node_modules/.pnpm/@prisma+client@4.13.0_prisma@4.13.0/node_modules/.prisma/client/index.js:3:11)
    at 2415 (/app/.next/server/chunks/415.js:18:16)
    at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:25:42)
    at 639 (/app/.next/server/chunks/639.js:26:77)
    at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:25:42)
    at __webpack_exec__ (/app/.next/server/pages/api/auth/[...nextauth].js:56:39)
    at /app/.next/server/pages/api/auth/[...nextauth].js:57:70
    at __webpack_require__.X (/app/.next/server/webpack-api-runtime.js:177:21)
    at /app/.next/server/pages/api/auth/[...nextauth].js:57:47
    at Object.<anonymous> (/app/.next/server/pages/api/auth/[...nextauth].js:60:3)

### To reproduce

Listening on port 3000 url: http://9f360ba7399b:3000
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/app/node_modules/.pnpm/@prisma+client@4.13.0_prisma@4.13.0/node_modules/.prisma/client/index.js:3:11)
    at 2415 (/app/.next/server/chunks/415.js:18:16)
    at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:25:42)
    at 639 (/app/.next/server/chunks/639.js:26:77)
    at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:25:42)
    at __webpack_exec__ (/app/.next/server/pages/api/auth/[...nextauth].js:56:39)
    at /app/.next/server/pages/api/auth/[...nextauth].js:57:70
    at __webpack_require__.X (/app/.next/server/webpack-api-runtime.js:177:21)
    at /app/.next/server/pages/api/auth/[...nextauth].js:57:47
    at Object.<anonymous> (/app/.next/server/pages/api/auth/[...nextauth].js:60:3)
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/app/node_modules/.pnpm/@prisma+client@4.13.0_prisma@4.13.0/node_modules/.prisma/client/index.js:3:11)
    at 2415 (/app/.next/server/chunks/415.js:18:16)
    at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:25:42)
    at 639 (/app/.next/server/chunks/639.js:26:77)
    at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:25:42)
    at __webpack_exec__ (/app/.next/server/pages/api/auth/[...nextauth].js:56:39)
    at /app/.next/server/pages/api/auth/[...nextauth].js:57:70
    at __webpack_require__.X (/app/.next/server/webpack-api-runtime.js:177:21)
    at /app/.next/server/pages/api/auth/[...nextauth].js:57:47
    at Object.<anonymous> (/app/.next/server/pages/api/auth/[...nextauth].js:60:3)

**Comment by WQMysqlDBA** [comment]
i have installed sqlchat in docker ，then run containers get this errors

**Comment by tianzhou** [comment]
Fixed in https://github.com/sqlchat/sqlchat/commit/718b75baffc9750a7314c0b0a2cb610eb2488a72.

Please pull the image again.
