### ISSUE TITLE
Network problem, failed to connect to Open AI server

### ISSUE THREAD

**Issue by anyi1998** [sqlchat/sqlchat#40]
### Describe the bug

1.git clone splchat项目下来
2.添加.env文件，输入api key，OPENAI_API_KEY= XXXX
2.pnpm i && pnpm dev
3.进入localhost：3000，打开项目后，正常聊天，显示500网络失败；左下角setting弹窗里面添加过自己的key之后也失败

背景： 网络环境ok，postman测试https://api.openai.com/v1/chat/completions接口正常使用

网络信息：
Request URL: http://localhost:3000/api/chat
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: [::1]:3000
Referrer Policy: strict-origin-when-cross-origin
Cache-Control: no-store, must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html; charset=utf-8
Date: Wed, 19 Apr 2023 03:22:49 GMT
ETag: "ofxhq550gm2rz"
Keep-Alive: timeout=5
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Powered-By: Next.js
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Connection: keep-alive
Content-Length: 1588
Content-Type: text/plain;charset=UTF-8
Host: localhost:3000
Origin: http://localhost:3000
Referer: http://localhost:3000/

### To reproduce

无

**Comment by anyi1998** [comment]
需要连接数据库吗？还是说需要修改代理配置让它能正常访问，nextJs和docker不是很熟，后端内容也不太会，麻烦帮忙解答下

**Comment by anyi1998** [comment]
error - Error [TypeError]: fetch failed
    at context.fetch (file://D:\Users\Desktop\project\sqlchat\node_modules\.pnpm\next@13.2.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\web\sandbox\context.js:167:38)
    at Object.handler (webpack-internal:///(middleware)/./src/pages/api/chat.ts:23:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async adapter (webpack-internal:///(middleware)/./node_modules/.pnpm/next@13.2.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/web/adapter.js:118:20)
    at async (file://D:\Users\Desktop\project\sqlchat\node_modules\.pnpm\next@13.2.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\web\sandbox\sandbox.js:74:24)
    at async DevServer.runEdgeFunction (file://D:\Users\Desktop\project\sqlchat\node_modules\.pnpm\next@13.2.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\next-server.js:1443:24)
    at async Object.fn (file://D:\Users\Desktop\project\sqlchat\node_modules\.pnpm\next@13.2.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\next-server.js:801:59)
    at async Router.execute (file://D:\Users\Desktop\project\sqlchat\node_modules\.pnpm\next@13.2.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\router.js:243:32)
    at async DevServer.runImpl (file://D:\Users\Desktop\project\sqlchat\node_modules\.pnpm\next@13.2.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:432:29)
    at async DevServer.run (file://D:\Users\Desktop\project\sqlchat\node_modules\.pnpm\next@13.2.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:831:20)
    at async DevServer.handleRequestImpl (file://D:\Users\Desktop\project\sqlchat\node_modules\.pnpm\next@13.2.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:375:20)
    at async (file://D:\Users\Desktop\project\sqlchat\node_modules\.pnpm\next@13.2.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:157:99)

**Comment by anyi1998** [comment]
上面是报错信息

**Comment by yuzhen9** [comment]
我和你一样的问题，使用clash for Windows的tun模式就可以了
