### ISSUE TITLE
Copy to clipboard not working

### ISSUE THREAD

**Issue by 57ggfk** [sqlchat/sqlchat#42]
### Describe the bug

我用docker部署的，或者是我用nginx代理https://www.sqlchat.ai/的，都不能使用复制功能。

### To reproduce

浏览器报错信息如下：
Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at f (699.f0bb0a7d606b128c.js:1:7508)
    at 58.f549a9ce3638af24.js:1:4539
    at Object.eU (framework-281bd828f4ecdac7.js:9:14914)
    at eH (framework-281bd828f4ecdac7.js:9:15068)
    at framework-281bd828f4ecdac7.js:9:33376
    at re (framework-281bd828f4ecdac7.js:9:33475)
    at rn (framework-281bd828f4ecdac7.js:9:33889)
    at framework-281bd828f4ecdac7.js:9:39347
    at oP (framework-281bd828f4ecdac7.js:9:96347)
    at eF (framework-281bd828f4ecdac7.js:9:14048)
追踪到语句：navigator.clipboard.writeText(s.content),
执行navigator.clipboard返回undefined

**Comment by boojack** [comment]
@57ggfk Which browser are you using?

**Comment by boojack** [comment]
Maybe solved by #43, please try again.
